name: Run R Script and Save Results

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar R no ambiente
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::googleway
            any::git2r
    
          
      # Rodar o script R
      - name: Run R script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}  # Acesso seguro à chave API
          GITHUB_TOKEN: ${{ secrets.GMAP_GIT }} #  Acesso seguro ao Git
        run: |
          Rscript script1.R  # Certifique-se de que o script esteja no diretório raiz ou ajuste o caminho

      # Commit e push dos resultados
      - name: Commit and push results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Atualizando dados de distância"
          git push
        
