# .github/workflows/distance_workflow.yml  

name: Get Distance from Google Maps API  

on:  
  workflow_dispatch:  
    inputs:  
      origin:  
        description: 'Coordenadas de origem (ex: "lat,lng")'  
        required: true  
      destination:  
        description: 'Coordenadas de destino (ex: "lat,lng")'  
        required: true  

jobs:  
  get_distance:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Checar out o código  
      uses: actions/checkout@v2  

    - name: Configurar Node.js  
      uses: actions/setup-node@v2  
      with:  
        node-version: '18'  

    - name: Instalar dependências  
      run: npm install axios  

    - name: Obter distância  
      run: node getDistance.js "${{ github.event.inputs.origin }}" "${{ github.event.inputs.destination }}"  
      env:  
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
